version: "3"

services:
  elixir_server:
    image: hexpm/elixir:1.18.4-erlang-27.3.3-debian-buster-20240612
    command: tail -f /dev/null
    container_name: elixir_server
    environment:
      - AWS_ACCESS_KEY_ID=GK21f88119e76b969d6a1ae052
      - AWS_SECRET_ACCESS_KEY=abf070f8d57bc050c4c2bcc3fba6cc70028441ade9c5fc6d87d9a7b5f9949eff
    networks:
      - wikipedia_data_processing_network
    restart: unless-stopped
    volumes:
      - "./:/wiki_data_processing"
    working_dir: /wiki_data_processing

  garage:
    image: dxflrs/garage:v2.0.0
    container_name: garage
    networks:
      - wikipedia_data_processing_network
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
      - wiki-elixir-garage-data:/var/lib/garage

  garage-webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    depends_on:
      garage:
        condition: service_started
    networks:
      - wikipedia_data_processing_network
    restart: unless-stopped
    volumes:
      - ./garage/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

volumes:
  wiki-elixir-garage-data:

networks:
  wikipedia_data_processing_network:
    external: true
