version: "3"

networks:
  app_network:

services:
  elixir_server:
    image: hexpm/elixir:1.18.4-erlang-27.3.3-debian-buster-20240612
    command: tail -f /dev/null
    container_name: elixir_server
    environment:
      - AWS_ACCESS_KEY_ID=minio_root_user
      - AWS_SECRET_ACCESS_KEY=minio_root_pass
    networks:
      - wikipeddia_data_processing_network
    restart: unless-stopped
    volumes:
      - "./:/wiki_data_processing"
    working_dir: /wiki_data_processing

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: minio
    networks:
      - wikipeddia_data_processing_network
    ports:
      - "6060:6060"
      - "6001:6001"
    volumes:
      - wiki-elixir-minio-data:/data
    environment:
      - MINIO_ROOT_USER=minio_root_user
      - MINIO_ROOT_PASSWORD=minio_root_pass
    command: server --address 0.0.0.0:6060 --console-address ":6001" /data
    restart: always
    logging:
      driver: "local"
      options:
        max-size: 10m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6060/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  wiki-elixir-minio-data:

networks:
  wikipeddia_data_processing_network:
    external: true
